### ISSUE TITLE
[Bug]: Housing server problems

### ISSUE THREAD

**Issue by Kage0x3B** [RaidRun/.github#90]
### ✅ Todo

- [ ] View distance is set too high, players can see other islands
- [ ] Does the build space expand correctly? While it should expand to include anything behind or around the balloon, it only expands in 2 out of 4 directions.
- [ ] Void world generator not working?
- [ ] Falling into the void respawns the player at a slightly wrong position *inside* the wood of the balloon
- [ ] Maybe fix the "can't build message" to not include the "expand your build space" part when building near the balloon.
- [ ] Sometimes the grass item from the expand build space gui can get into the player inventory as an actual item (transferable to other servers. Might happen after the diamond trade, when the space can't be expanded anymore)
